//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingChallenge.Data.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Círculos.
        /// </summary>
        internal static string Circulo_PLURAL {
            get {
                return ResourceManager.GetString("Circulo_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Círculo.
        /// </summary>
        internal static string Circulo_SINGULAR {
            get {
                return ResourceManager.GetString("Circulo_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuadrados.
        /// </summary>
        internal static string Cuadrado_PLURAR {
            get {
                return ResourceManager.GetString("Cuadrado_PLURAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuadrado.
        /// </summary>
        internal static string Cuadrado_SINGULAR {
            get {
                return ResourceManager.GetString("Cuadrado_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h1&gt;Reporte de Formas&lt;/h1&gt;.
        /// </summary>
        internal static string Encabezado_Reporte {
            get {
                return ResourceManager.GetString("Encabezado_Reporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h1&gt;Lista vacía de formas!&lt;/h1&gt;.
        /// </summary>
        internal static string Lista_Vacia {
            get {
                return ResourceManager.GetString("Lista_Vacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rectángulos.
        /// </summary>
        internal static string Rectangulo_PLURAL {
            get {
                return ResourceManager.GetString("Rectangulo_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rectángulo.
        /// </summary>
        internal static string Rectangulo_SINGULAR {
            get {
                return ResourceManager.GetString("Rectangulo_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} {1} | Area {2:#.##} | Perimetro {3:#.##} &lt;br/&gt;.
        /// </summary>
        internal static string Reporte_CUERPO_DETALLE {
            get {
                return ResourceManager.GetString("Reporte_CUERPO_DETALLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area {0:#.##} .
        /// </summary>
        internal static string Reporte_PIE_TOTAL_AREA {
            get {
                return ResourceManager.GetString("Reporte_PIE_TOTAL_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Formas.
        /// </summary>
        internal static string Reporte_PIE_TOTAL_FORMAS {
            get {
                return ResourceManager.GetString("Reporte_PIE_TOTAL_FORMAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perimetro {0:#.##}.
        /// </summary>
        internal static string Reporte_PIE_TOTAL_PERIMETRO {
            get {
                return ResourceManager.GetString("Reporte_PIE_TOTAL_PERIMETRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapecio Isoceles.
        /// </summary>
        internal static string Trapecio_Isoceles_SINGULAR {
            get {
                return ResourceManager.GetString("Trapecio_Isoceles_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapecios Isoceles.
        /// </summary>
        internal static string Trapecios_Isoceles_PLURAL {
            get {
                return ResourceManager.GetString("Trapecios_Isoceles_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triángulo Equilatero.
        /// </summary>
        internal static string Triangulo_Equilarero_SINGULAR {
            get {
                return ResourceManager.GetString("Triangulo_Equilarero_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triángulos Equilateros.
        /// </summary>
        internal static string Triangulo_Equilatero_PLURAL {
            get {
                return ResourceManager.GetString("Triangulo_Equilatero_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triángulos Isoceles.
        /// </summary>
        internal static string Triangulo_Isoceles_PLURAL {
            get {
                return ResourceManager.GetString("Triangulo_Isoceles_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triángulo Isoceles.
        /// </summary>
        internal static string Triangulo_Isoceles_SINGULAR {
            get {
                return ResourceManager.GetString("Triangulo_Isoceles_SINGULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triángulos.
        /// </summary>
        internal static string Triangulo_PLURAL {
            get {
                return ResourceManager.GetString("Triangulo_PLURAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triángulo.
        /// </summary>
        internal static string Triangulo_SINGULAR {
            get {
                return ResourceManager.GetString("Triangulo_SINGULAR", resourceCulture);
            }
        }
    }
}
